version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 0 # disable
    versioning-strategy: increase
    directory: '/'
    commit-message:
      prefix: '📦 chore'
      include: 'scope'
    assignees:
      - 'CS-Tao'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: 'fs-extra'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
