name: CD for WHU-Court

on: [push]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 18]
        include:
          - os: windows-latest
            node: 16
            npm: 6
          - os: macos-latest
            node: 16
            npm: 6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ matrix.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn cd:check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ runner.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - run: yarn cd:release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
